In [ ]:
import pandas as pd

In [ ]:
def smiti_minimum_edit_distance(s1, s2, insert_cost_smiti=1, delete_cost_smiti=1, substitute_cost=1):
  m = len(s1)
  n = len(s2)

  dp = [[0 for _ in range(n+1)] for _ in range(m+1)]

  for i in range(m+1):
    dp[i][0] = i * delete_cost_smiti
  for j in range(n+1):
    dp[0][j] = j * insert_cost_smiti

  for i in range(1, m+1):
    for j in range(1, n+1):
      if s1[i-1] == s2[j-1]:
        cost = 0
      else:
        cost = substitute_cost

      dp[i][j] = min(
          dp[i-1][j] + delete_cost_smiti,
          dp[i][j-1] + insert_cost_smiti,
          dp[i-1][j-1] + cost
      )
  return dp, dp[m][n]

def show_dp_table(s1, s2, dp):
  df = pd.DataFrame(dp, index=[''] + list(s1), columns=[''] + list(s2))
  display(df)

**Test Cases**

In [ ]:
test_cases = [
    ("kitten", "sitting"),        #Substitution + insertion
    ("book", "back"),             #Substitution
    ("intention", "execution"),   #Complex changes
    ("speling", "spelling"),      #typo(insertion)
    ("playing", "play"),          # deletion
]

for s1, s2 in test_cases:
  dp_table, distance = smiti_minimum_edit_distance(s1, s2)
  print(f"Source String: {s1}")
  print(f"Target String: {s2}")
  print(f"Minimum Edit Distance: {distance}")
  show_dp_table(s1, s2, dp_table)

Source String: kitten
Target String: sitting
Minimum Edit Distance: 3

      s  i  t  t  i  n  g
   0  1  2  3  4  5  6  7
k  1  1  2  3  4  5  6  7
i  2  2  1  2  3  4  5  6
t  3  3  2  1  2  3  4  5
t  4  4  3  2  1  2  3  4
e  5  5  4  3  2  2  3  4
n  6  6  5  4  3  3  2  3

Source String: book
Target String: back
Minimum Edit Distance: 2

      b  a  c  k
   0  1  2  3  4
b  1  0  1  2  3
o  2  1  1  2  3
o  3  2  2  2  3
k  4  3  3  3  2

Source String: intention
Target String: execution
Minimum Edit Distance: 5

      e  x  e  c  u  t  i  o  n
   0  1  2  3  4  5  6  7  8  9
i  1  1  2  3  4  5  6  6  7  8
n  2  2  2  3  4  5  6  7  7  7
t  3  3  3  3  4  5  5  6  7  8
e  4  3  4  3  4  5  6  6  7  8
n  5  4  4  4  4  5  6  7  7  7
t  6  5  5  5  5  5  5  6  7  8
i  7  6  6  6  6  6  6  5  6  7
o  8  7  7  7  7  7  7  6  5  6
n  9  8  8  8  8  8  8  7  6  5

Source String: speling
Target String: spelling
Minimum Edit Distance: 1

      s  p  e  l  l  i  n  g
   0  1  2  3  4  5  6  7  8
s  1  0  1  2  3  4  5  6  7
p  2  1  0  1  2  3  4  5  6
e  3  2  1  0  1  2  3  4  5
l  4  3  2  1  0  1  2  3  4
i  5  4  3  2  1  1  1  2  3
n  6  5  4  3  2  2  2  1  2
g  7  6  5  4  3  3  3  2  1

Source String: playing
Target String: play
Minimum Edit Distance: 3

      p  l  a  y
   0  1  2  3  4
p  1  0  1  2  3
l  2  1  0  1  2
a  3  2  1  0  1
y  4  3  2  1  0
i  5  4  3  2  1
n  6  5  4  3  2
g  7  6  5  4  3

**Adaptability Test**

In [ ]:
print("Adaptability Test (Different Costs)")
s1 = "colour"
s2 = "color"

dp_table, distance = smiti_minimum_edit_distance(s1, s2, substitute_cost=2)
print("Source: ", s1)
print("Target: ", s2)
print("Edit Distance(Substitution Cost = 2): ", distance)
show_dp_table(s1, s2, dp_table)

Adaptability Test (Different Costs)
Source:  colour
Target:  color
Edit Distance(Substitution Cost = 2):  1

      c  o  l  o  r
   0  1  2  3  4  5
c  1  0  1  2  3  4
o  2  1  0  1  2  3
l  3  2  1  0  1  2
o  4  3  2  1  0  1
u  5  4  3  2  1  2
r  6  5  4  3  2  1